version: '3'

services:
  report:
    image: golang:1.15
    container_name: "request-log"
    ports:
      - "80:80"
      - "443:443"
    working_dir: "/go/src/gitlab.com/tsuchinaga/go-web-request-log"
    volumes:
      - "./:/go/src/gitlab.com/tsuchinaga/go-web-request-log"
    environment:
      - TZ=Asia/Tokyo
      - HOST=localhost
    tty: true
    command: go run main.go
